#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_kandydata
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Demo2018")]
	public partial class HmfModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTW(TW instance);
    partial void UpdateTW(TW instance);
    partial void DeleteTW(TW instance);
    partial void Insertmplerpsw_configuration(mplerpsw_configuration instance);
    partial void Updatemplerpsw_configuration(mplerpsw_configuration instance);
    partial void Deletemplerpsw_configuration(mplerpsw_configuration instance);
    partial void Insertmplerpsw_right(mplerpsw_right instance);
    partial void Updatemplerpsw_right(mplerpsw_right instance);
    partial void Deletemplerpsw_right(mplerpsw_right instance);
    partial void InsertSF_ACTIVITIES_LOG(SF_ACTIVITIES_LOG instance);
    partial void UpdateSF_ACTIVITIES_LOG(SF_ACTIVITIES_LOG instance);
    partial void DeleteSF_ACTIVITIES_LOG(SF_ACTIVITIES_LOG instance);
    #endregion
		
		public HmfModelDataContext() : 
				base(global::Test_kandydata.Properties.Settings.Default.Demo2018ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HmfModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HmfModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HmfModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HmfModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vKontrahenci> vKontrahencis
		{
			get
			{
				return this.GetTable<vKontrahenci>();
			}
		}
		
		public System.Data.Linq.Table<vAdresyKh> vAdresyKhs
		{
			get
			{
				return this.GetTable<vAdresyKh>();
			}
		}
		
		public System.Data.Linq.Table<TW> TWs
		{
			get
			{
				return this.GetTable<TW>();
			}
		}
		
		public System.Data.Linq.Table<SF_PRICEBOOK> SF_PRICEBOOKs
		{
			get
			{
				return this.GetTable<SF_PRICEBOOK>();
			}
		}
		
		public System.Data.Linq.Table<SF_ACCOUNT> SF_ACCOUNTs
		{
			get
			{
				return this.GetTable<SF_ACCOUNT>();
			}
		}
		
		public System.Data.Linq.Table<mplerpsw_configuration> mplerpsw_configurations
		{
			get
			{
				return this.GetTable<mplerpsw_configuration>();
			}
		}
		
		public System.Data.Linq.Table<mplerpsw_right> mplerpsw_rights
		{
			get
			{
				return this.GetTable<mplerpsw_right>();
			}
		}
		
		public System.Data.Linq.Table<SF_PRICEBOOKS_GROSS> SF_PRICEBOOKS_GROSSes
		{
			get
			{
				return this.GetTable<SF_PRICEBOOKS_GROSS>();
			}
		}
		
		public System.Data.Linq.Table<SF_ACTIVITIES_LOG> SF_ACTIVITIES_LOGs
		{
			get
			{
				return this.GetTable<SF_ACTIVITIES_LOG>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="HM.hm_GetUpustIndyw")]
		public ISingleResult<hm_GetUpustIndywResult> hm_GetUpustIndyw([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPm, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idRodzPm, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idRodzPd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallInt")] System.Nullable<short> aktywna, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallInt")] System.Nullable<short> typ)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPm, idPd, idRodzPm, idRodzPd, aktywna, typ);
			return ((ISingleResult<hm_GetUpustIndywResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sf_InsertSFDCOrderNumber")]
		public int sf_InsertSFDCOrderNumber([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ZOid", DbType="Int")] System.Nullable<int> zOid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SFDCOrderNumber", DbType="VarChar(50)")] string sFDCOrderNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), zOid, sFDCOrderNumber);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="SSCommon.vKontrahenci")]
	public partial class vKontrahenci
	{
		
		private int _id;
		
		private System.Guid _guid;
		
		private string _kod;
		
		private string _nazwa;
		
		private string _nip;
		
		private bool _limit;
		
		private double _limitKwota;
		
		private string _limitWaluta;
		
		private bool _aktywny;
		
		private string _znacznik;
		
		private int _rodzaj;
		
		private string _katalog;
		
		private System.Nullable<int> _idKraju;
		
		private string _miejscowosc;
		
		private string _rejon;
		
		private string _kodpocz;
		
		public vKontrahenci()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid guid
		{
			get
			{
				return this._guid;
			}
			set
			{
				if ((this._guid != value))
				{
					this._guid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kod", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string kod
		{
			get
			{
				return this._kod;
			}
			set
			{
				if ((this._kod != value))
				{
					this._kod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string nazwa
		{
			get
			{
				return this._nazwa;
			}
			set
			{
				if ((this._nazwa != value))
				{
					this._nazwa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nip", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string nip
		{
			get
			{
				return this._nip;
			}
			set
			{
				if ((this._nip != value))
				{
					this._nip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_limit", DbType="Bit NOT NULL")]
		public bool limit
		{
			get
			{
				return this._limit;
			}
			set
			{
				if ((this._limit != value))
				{
					this._limit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_limitKwota", DbType="Float NOT NULL")]
		public double limitKwota
		{
			get
			{
				return this._limitKwota;
			}
			set
			{
				if ((this._limitKwota != value))
				{
					this._limitKwota = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_limitWaluta", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string limitWaluta
		{
			get
			{
				return this._limitWaluta;
			}
			set
			{
				if ((this._limitWaluta != value))
				{
					this._limitWaluta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aktywny", DbType="Bit NOT NULL")]
		public bool aktywny
		{
			get
			{
				return this._aktywny;
			}
			set
			{
				if ((this._aktywny != value))
				{
					this._aktywny = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_znacznik", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string znacznik
		{
			get
			{
				return this._znacznik;
			}
			set
			{
				if ((this._znacznik != value))
				{
					this._znacznik = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rodzaj", DbType="Int NOT NULL")]
		public int rodzaj
		{
			get
			{
				return this._rodzaj;
			}
			set
			{
				if ((this._rodzaj != value))
				{
					this._rodzaj = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_katalog", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string katalog
		{
			get
			{
				return this._katalog;
			}
			set
			{
				if ((this._katalog != value))
				{
					this._katalog = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKraju", DbType="Int")]
		public System.Nullable<int> idKraju
		{
			get
			{
				return this._idKraju;
			}
			set
			{
				if ((this._idKraju != value))
				{
					this._idKraju = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_miejscowosc", DbType="NVarChar(50)")]
		public string miejscowosc
		{
			get
			{
				return this._miejscowosc;
			}
			set
			{
				if ((this._miejscowosc != value))
				{
					this._miejscowosc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rejon", DbType="NVarChar(50)")]
		public string rejon
		{
			get
			{
				return this._rejon;
			}
			set
			{
				if ((this._rejon != value))
				{
					this._rejon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kodpocz", DbType="NVarChar(10)")]
		public string kodpocz
		{
			get
			{
				return this._kodpocz;
			}
			set
			{
				if ((this._kodpocz != value))
				{
					this._kodpocz = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="SSCommon.vAdresyKh")]
	public partial class vAdresyKh
	{
		
		private int _idkh;
		
		private System.Nullable<int> _id;
		
		private string _nazwaAdr;
		
		private string _ulica;
		
		private string _dom;
		
		private string _lokal;
		
		private string _miejscowosc;
		
		private string _kodpocz;
		
		private string _kraj;
		
		public vAdresyKh()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idkh", DbType="Int NOT NULL")]
		public int idkh
		{
			get
			{
				return this._idkh;
			}
			set
			{
				if ((this._idkh != value))
				{
					this._idkh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
		public System.Nullable<int> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwaAdr", DbType="NVarChar(64)")]
		public string nazwaAdr
		{
			get
			{
				return this._nazwaAdr;
			}
			set
			{
				if ((this._nazwaAdr != value))
				{
					this._nazwaAdr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ulica", DbType="NVarChar(50)")]
		public string ulica
		{
			get
			{
				return this._ulica;
			}
			set
			{
				if ((this._ulica != value))
				{
					this._ulica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dom", DbType="NVarChar(15)")]
		public string dom
		{
			get
			{
				return this._dom;
			}
			set
			{
				if ((this._dom != value))
				{
					this._dom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lokal", DbType="NVarChar(15)")]
		public string lokal
		{
			get
			{
				return this._lokal;
			}
			set
			{
				if ((this._lokal != value))
				{
					this._lokal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_miejscowosc", DbType="NVarChar(50)")]
		public string miejscowosc
		{
			get
			{
				return this._miejscowosc;
			}
			set
			{
				if ((this._miejscowosc != value))
				{
					this._miejscowosc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kodpocz", DbType="NVarChar(10)")]
		public string kodpocz
		{
			get
			{
				return this._kodpocz;
			}
			set
			{
				if ((this._kodpocz != value))
				{
					this._kodpocz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kraj", DbType="NVarChar(50)")]
		public string kraj
		{
			get
			{
				return this._kraj;
			}
			set
			{
				if ((this._kraj != value))
				{
					this._kraj = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="HM.TW")]
	public partial class TW : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private short _flag;
		
		private bool _aktywny;
		
		private short _subtyp;
		
		private short _typ;
		
		private short _znacznik;
		
		private System.Nullable<int> _rodzaj;
		
		private System.Nullable<int> _katalog;
		
		private short _info;
		
		private string _kod;
		
		private string _nazwa;
		
		private string _kodpaskowy;
		
		private System.Nullable<int> _vatsp;
		
		private string _sww;
		
		private short _zaokrag;
		
		private System.Nullable<int> _idlongname;
		
		private string _kontofk;
		
		private short _metoda;
		
		private short _przelicz;
		
		private string _szablon;
		
		private string _nazwaFiskal;
		
		private string _jmdod1;
		
		private double _przeljmdod1;
		
		private string _jmdod2;
		
		private double _przeljmdod2;
		
		private double _stanmin;
		
		private double _stanmax;
		
		private string _typks;
		
		private string _jm;
		
		private short _jmdef;
		
		private string _jmdom;
		
		private double _przeljmdom;
		
		private short _negoc;
		
		private System.Nullable<int> _super;
		
		private System.Nullable<int> _createdBy;
		
		private System.Nullable<System.DateTime> _createdDate;
		
		private System.Nullable<int> _modifiedBy;
		
		private System.Nullable<System.DateTime> _modifiedDate;
		
		private string _pcn;
		
		private double _przelkg;
		
		private double _przeluz;
		
		private short _przelit;
		
		private string _jmuzup;
		
		private int _fundusz;
		
		private short _odwrotneObc;
		
		private short _vat50;
		
		private EntitySet<TW> _TWs;
		
		private EntityRef<TW> _TW1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnflagChanging(short value);
    partial void OnflagChanged();
    partial void OnaktywnyChanging(bool value);
    partial void OnaktywnyChanged();
    partial void OnsubtypChanging(short value);
    partial void OnsubtypChanged();
    partial void OntypChanging(short value);
    partial void OntypChanged();
    partial void OnznacznikChanging(short value);
    partial void OnznacznikChanged();
    partial void OnrodzajChanging(System.Nullable<int> value);
    partial void OnrodzajChanged();
    partial void OnkatalogChanging(System.Nullable<int> value);
    partial void OnkatalogChanged();
    partial void OninfoChanging(short value);
    partial void OninfoChanged();
    partial void OnkodChanging(string value);
    partial void OnkodChanged();
    partial void OnnazwaChanging(string value);
    partial void OnnazwaChanged();
    partial void OnkodpaskowyChanging(string value);
    partial void OnkodpaskowyChanged();
    partial void OnvatspChanging(System.Nullable<int> value);
    partial void OnvatspChanged();
    partial void OnswwChanging(string value);
    partial void OnswwChanged();
    partial void OnzaokragChanging(short value);
    partial void OnzaokragChanged();
    partial void OnidlongnameChanging(System.Nullable<int> value);
    partial void OnidlongnameChanged();
    partial void OnkontofkChanging(string value);
    partial void OnkontofkChanged();
    partial void OnmetodaChanging(short value);
    partial void OnmetodaChanged();
    partial void OnprzeliczChanging(short value);
    partial void OnprzeliczChanged();
    partial void OnszablonChanging(string value);
    partial void OnszablonChanged();
    partial void OnnazwaFiskalChanging(string value);
    partial void OnnazwaFiskalChanged();
    partial void Onjmdod1Changing(string value);
    partial void Onjmdod1Changed();
    partial void Onprzeljmdod1Changing(double value);
    partial void Onprzeljmdod1Changed();
    partial void Onjmdod2Changing(string value);
    partial void Onjmdod2Changed();
    partial void Onprzeljmdod2Changing(double value);
    partial void Onprzeljmdod2Changed();
    partial void OnstanminChanging(double value);
    partial void OnstanminChanged();
    partial void OnstanmaxChanging(double value);
    partial void OnstanmaxChanged();
    partial void OntypksChanging(string value);
    partial void OntypksChanged();
    partial void OnjmChanging(string value);
    partial void OnjmChanged();
    partial void OnjmdefChanging(short value);
    partial void OnjmdefChanged();
    partial void OnjmdomChanging(string value);
    partial void OnjmdomChanged();
    partial void OnprzeljmdomChanging(double value);
    partial void OnprzeljmdomChanged();
    partial void OnnegocChanging(short value);
    partial void OnnegocChanged();
    partial void OnsuperChanging(System.Nullable<int> value);
    partial void OnsuperChanged();
    partial void OncreatedByChanging(System.Nullable<int> value);
    partial void OncreatedByChanged();
    partial void OncreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedDateChanged();
    partial void OnmodifiedByChanging(System.Nullable<int> value);
    partial void OnmodifiedByChanged();
    partial void OnmodifiedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnmodifiedDateChanged();
    partial void OnpcnChanging(string value);
    partial void OnpcnChanged();
    partial void OnprzelkgChanging(double value);
    partial void OnprzelkgChanged();
    partial void OnprzeluzChanging(double value);
    partial void OnprzeluzChanged();
    partial void OnprzelitChanging(short value);
    partial void OnprzelitChanged();
    partial void OnjmuzupChanging(string value);
    partial void OnjmuzupChanged();
    partial void OnfunduszChanging(int value);
    partial void OnfunduszChanged();
    partial void OnodwrotneObcChanging(short value);
    partial void OnodwrotneObcChanged();
    partial void Onvat50Changing(short value);
    partial void Onvat50Changed();
    #endregion
		
		public TW()
		{
			this._TWs = new EntitySet<TW>(new Action<TW>(this.attach_TWs), new Action<TW>(this.detach_TWs));
			this._TW1 = default(EntityRef<TW>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag", DbType="SmallInt NOT NULL")]
		public short flag
		{
			get
			{
				return this._flag;
			}
			set
			{
				if ((this._flag != value))
				{
					this.OnflagChanging(value);
					this.SendPropertyChanging();
					this._flag = value;
					this.SendPropertyChanged("flag");
					this.OnflagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aktywny", DbType="Bit NOT NULL")]
		public bool aktywny
		{
			get
			{
				return this._aktywny;
			}
			set
			{
				if ((this._aktywny != value))
				{
					this.OnaktywnyChanging(value);
					this.SendPropertyChanging();
					this._aktywny = value;
					this.SendPropertyChanged("aktywny");
					this.OnaktywnyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subtyp", DbType="SmallInt NOT NULL")]
		public short subtyp
		{
			get
			{
				return this._subtyp;
			}
			set
			{
				if ((this._subtyp != value))
				{
					this.OnsubtypChanging(value);
					this.SendPropertyChanging();
					this._subtyp = value;
					this.SendPropertyChanged("subtyp");
					this.OnsubtypChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typ", DbType="SmallInt NOT NULL")]
		public short typ
		{
			get
			{
				return this._typ;
			}
			set
			{
				if ((this._typ != value))
				{
					this.OntypChanging(value);
					this.SendPropertyChanging();
					this._typ = value;
					this.SendPropertyChanged("typ");
					this.OntypChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_znacznik", DbType="SmallInt NOT NULL")]
		public short znacznik
		{
			get
			{
				return this._znacznik;
			}
			set
			{
				if ((this._znacznik != value))
				{
					this.OnznacznikChanging(value);
					this.SendPropertyChanging();
					this._znacznik = value;
					this.SendPropertyChanged("znacznik");
					this.OnznacznikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rodzaj", DbType="Int")]
		public System.Nullable<int> rodzaj
		{
			get
			{
				return this._rodzaj;
			}
			set
			{
				if ((this._rodzaj != value))
				{
					if (this._TW1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnrodzajChanging(value);
					this.SendPropertyChanging();
					this._rodzaj = value;
					this.SendPropertyChanged("rodzaj");
					this.OnrodzajChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_katalog", DbType="Int")]
		public System.Nullable<int> katalog
		{
			get
			{
				return this._katalog;
			}
			set
			{
				if ((this._katalog != value))
				{
					this.OnkatalogChanging(value);
					this.SendPropertyChanging();
					this._katalog = value;
					this.SendPropertyChanged("katalog");
					this.OnkatalogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_info", DbType="SmallInt NOT NULL")]
		public short info
		{
			get
			{
				return this._info;
			}
			set
			{
				if ((this._info != value))
				{
					this.OninfoChanging(value);
					this.SendPropertyChanging();
					this._info = value;
					this.SendPropertyChanged("info");
					this.OninfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kod", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string kod
		{
			get
			{
				return this._kod;
			}
			set
			{
				if ((this._kod != value))
				{
					this.OnkodChanging(value);
					this.SendPropertyChanging();
					this._kod = value;
					this.SendPropertyChanged("kod");
					this.OnkodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nazwa
		{
			get
			{
				return this._nazwa;
			}
			set
			{
				if ((this._nazwa != value))
				{
					this.OnnazwaChanging(value);
					this.SendPropertyChanging();
					this._nazwa = value;
					this.SendPropertyChanged("nazwa");
					this.OnnazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kodpaskowy", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string kodpaskowy
		{
			get
			{
				return this._kodpaskowy;
			}
			set
			{
				if ((this._kodpaskowy != value))
				{
					this.OnkodpaskowyChanging(value);
					this.SendPropertyChanging();
					this._kodpaskowy = value;
					this.SendPropertyChanged("kodpaskowy");
					this.OnkodpaskowyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vatsp", DbType="Int")]
		public System.Nullable<int> vatsp
		{
			get
			{
				return this._vatsp;
			}
			set
			{
				if ((this._vatsp != value))
				{
					this.OnvatspChanging(value);
					this.SendPropertyChanging();
					this._vatsp = value;
					this.SendPropertyChanged("vatsp");
					this.OnvatspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sww", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string sww
		{
			get
			{
				return this._sww;
			}
			set
			{
				if ((this._sww != value))
				{
					this.OnswwChanging(value);
					this.SendPropertyChanging();
					this._sww = value;
					this.SendPropertyChanged("sww");
					this.OnswwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zaokrag", DbType="SmallInt NOT NULL")]
		public short zaokrag
		{
			get
			{
				return this._zaokrag;
			}
			set
			{
				if ((this._zaokrag != value))
				{
					this.OnzaokragChanging(value);
					this.SendPropertyChanging();
					this._zaokrag = value;
					this.SendPropertyChanged("zaokrag");
					this.OnzaokragChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idlongname", DbType="Int")]
		public System.Nullable<int> idlongname
		{
			get
			{
				return this._idlongname;
			}
			set
			{
				if ((this._idlongname != value))
				{
					this.OnidlongnameChanging(value);
					this.SendPropertyChanging();
					this._idlongname = value;
					this.SendPropertyChanged("idlongname");
					this.OnidlongnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kontofk", DbType="VarChar(24) NOT NULL", CanBeNull=false)]
		public string kontofk
		{
			get
			{
				return this._kontofk;
			}
			set
			{
				if ((this._kontofk != value))
				{
					this.OnkontofkChanging(value);
					this.SendPropertyChanging();
					this._kontofk = value;
					this.SendPropertyChanged("kontofk");
					this.OnkontofkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_metoda", DbType="SmallInt NOT NULL")]
		public short metoda
		{
			get
			{
				return this._metoda;
			}
			set
			{
				if ((this._metoda != value))
				{
					this.OnmetodaChanging(value);
					this.SendPropertyChanging();
					this._metoda = value;
					this.SendPropertyChanged("metoda");
					this.OnmetodaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_przelicz", DbType="SmallInt NOT NULL")]
		public short przelicz
		{
			get
			{
				return this._przelicz;
			}
			set
			{
				if ((this._przelicz != value))
				{
					this.OnprzeliczChanging(value);
					this.SendPropertyChanging();
					this._przelicz = value;
					this.SendPropertyChanged("przelicz");
					this.OnprzeliczChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_szablon", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string szablon
		{
			get
			{
				return this._szablon;
			}
			set
			{
				if ((this._szablon != value))
				{
					this.OnszablonChanging(value);
					this.SendPropertyChanging();
					this._szablon = value;
					this.SendPropertyChanged("szablon");
					this.OnszablonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwaFiskal", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string nazwaFiskal
		{
			get
			{
				return this._nazwaFiskal;
			}
			set
			{
				if ((this._nazwaFiskal != value))
				{
					this.OnnazwaFiskalChanging(value);
					this.SendPropertyChanging();
					this._nazwaFiskal = value;
					this.SendPropertyChanged("nazwaFiskal");
					this.OnnazwaFiskalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jmdod1", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string jmdod1
		{
			get
			{
				return this._jmdod1;
			}
			set
			{
				if ((this._jmdod1 != value))
				{
					this.Onjmdod1Changing(value);
					this.SendPropertyChanging();
					this._jmdod1 = value;
					this.SendPropertyChanged("jmdod1");
					this.Onjmdod1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_przeljmdod1", DbType="Float NOT NULL")]
		public double przeljmdod1
		{
			get
			{
				return this._przeljmdod1;
			}
			set
			{
				if ((this._przeljmdod1 != value))
				{
					this.Onprzeljmdod1Changing(value);
					this.SendPropertyChanging();
					this._przeljmdod1 = value;
					this.SendPropertyChanged("przeljmdod1");
					this.Onprzeljmdod1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jmdod2", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string jmdod2
		{
			get
			{
				return this._jmdod2;
			}
			set
			{
				if ((this._jmdod2 != value))
				{
					this.Onjmdod2Changing(value);
					this.SendPropertyChanging();
					this._jmdod2 = value;
					this.SendPropertyChanged("jmdod2");
					this.Onjmdod2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_przeljmdod2", DbType="Float NOT NULL")]
		public double przeljmdod2
		{
			get
			{
				return this._przeljmdod2;
			}
			set
			{
				if ((this._przeljmdod2 != value))
				{
					this.Onprzeljmdod2Changing(value);
					this.SendPropertyChanging();
					this._przeljmdod2 = value;
					this.SendPropertyChanged("przeljmdod2");
					this.Onprzeljmdod2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stanmin", DbType="Float NOT NULL")]
		public double stanmin
		{
			get
			{
				return this._stanmin;
			}
			set
			{
				if ((this._stanmin != value))
				{
					this.OnstanminChanging(value);
					this.SendPropertyChanging();
					this._stanmin = value;
					this.SendPropertyChanged("stanmin");
					this.OnstanminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stanmax", DbType="Float NOT NULL")]
		public double stanmax
		{
			get
			{
				return this._stanmax;
			}
			set
			{
				if ((this._stanmax != value))
				{
					this.OnstanmaxChanging(value);
					this.SendPropertyChanging();
					this._stanmax = value;
					this.SendPropertyChanged("stanmax");
					this.OnstanmaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typks", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string typks
		{
			get
			{
				return this._typks;
			}
			set
			{
				if ((this._typks != value))
				{
					this.OntypksChanging(value);
					this.SendPropertyChanging();
					this._typks = value;
					this.SendPropertyChanged("typks");
					this.OntypksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jm", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string jm
		{
			get
			{
				return this._jm;
			}
			set
			{
				if ((this._jm != value))
				{
					this.OnjmChanging(value);
					this.SendPropertyChanging();
					this._jm = value;
					this.SendPropertyChanged("jm");
					this.OnjmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jmdef", DbType="SmallInt NOT NULL")]
		public short jmdef
		{
			get
			{
				return this._jmdef;
			}
			set
			{
				if ((this._jmdef != value))
				{
					this.OnjmdefChanging(value);
					this.SendPropertyChanging();
					this._jmdef = value;
					this.SendPropertyChanged("jmdef");
					this.OnjmdefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jmdom", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string jmdom
		{
			get
			{
				return this._jmdom;
			}
			set
			{
				if ((this._jmdom != value))
				{
					this.OnjmdomChanging(value);
					this.SendPropertyChanging();
					this._jmdom = value;
					this.SendPropertyChanged("jmdom");
					this.OnjmdomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_przeljmdom", DbType="Float NOT NULL")]
		public double przeljmdom
		{
			get
			{
				return this._przeljmdom;
			}
			set
			{
				if ((this._przeljmdom != value))
				{
					this.OnprzeljmdomChanging(value);
					this.SendPropertyChanging();
					this._przeljmdom = value;
					this.SendPropertyChanged("przeljmdom");
					this.OnprzeljmdomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_negoc", DbType="SmallInt NOT NULL")]
		public short negoc
		{
			get
			{
				return this._negoc;
			}
			set
			{
				if ((this._negoc != value))
				{
					this.OnnegocChanging(value);
					this.SendPropertyChanging();
					this._negoc = value;
					this.SendPropertyChanged("negoc");
					this.OnnegocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_super", DbType="Int")]
		public System.Nullable<int> super
		{
			get
			{
				return this._super;
			}
			set
			{
				if ((this._super != value))
				{
					this.OnsuperChanging(value);
					this.SendPropertyChanging();
					this._super = value;
					this.SendPropertyChanged("super");
					this.OnsuperChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdBy", DbType="Int")]
		public System.Nullable<int> createdBy
		{
			get
			{
				return this._createdBy;
			}
			set
			{
				if ((this._createdBy != value))
				{
					this.OncreatedByChanging(value);
					this.SendPropertyChanging();
					this._createdBy = value;
					this.SendPropertyChanged("createdBy");
					this.OncreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> createdDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				if ((this._createdDate != value))
				{
					this.OncreatedDateChanging(value);
					this.SendPropertyChanging();
					this._createdDate = value;
					this.SendPropertyChanged("createdDate");
					this.OncreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifiedBy", DbType="Int")]
		public System.Nullable<int> modifiedBy
		{
			get
			{
				return this._modifiedBy;
			}
			set
			{
				if ((this._modifiedBy != value))
				{
					this.OnmodifiedByChanging(value);
					this.SendPropertyChanging();
					this._modifiedBy = value;
					this.SendPropertyChanged("modifiedBy");
					this.OnmodifiedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifiedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> modifiedDate
		{
			get
			{
				return this._modifiedDate;
			}
			set
			{
				if ((this._modifiedDate != value))
				{
					this.OnmodifiedDateChanging(value);
					this.SendPropertyChanging();
					this._modifiedDate = value;
					this.SendPropertyChanged("modifiedDate");
					this.OnmodifiedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pcn", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string pcn
		{
			get
			{
				return this._pcn;
			}
			set
			{
				if ((this._pcn != value))
				{
					this.OnpcnChanging(value);
					this.SendPropertyChanging();
					this._pcn = value;
					this.SendPropertyChanged("pcn");
					this.OnpcnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_przelkg", DbType="Float NOT NULL")]
		public double przelkg
		{
			get
			{
				return this._przelkg;
			}
			set
			{
				if ((this._przelkg != value))
				{
					this.OnprzelkgChanging(value);
					this.SendPropertyChanging();
					this._przelkg = value;
					this.SendPropertyChanged("przelkg");
					this.OnprzelkgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_przeluz", DbType="Float NOT NULL")]
		public double przeluz
		{
			get
			{
				return this._przeluz;
			}
			set
			{
				if ((this._przeluz != value))
				{
					this.OnprzeluzChanging(value);
					this.SendPropertyChanging();
					this._przeluz = value;
					this.SendPropertyChanged("przeluz");
					this.OnprzeluzChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_przelit", DbType="SmallInt NOT NULL")]
		public short przelit
		{
			get
			{
				return this._przelit;
			}
			set
			{
				if ((this._przelit != value))
				{
					this.OnprzelitChanging(value);
					this.SendPropertyChanging();
					this._przelit = value;
					this.SendPropertyChanged("przelit");
					this.OnprzelitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jmuzup", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string jmuzup
		{
			get
			{
				return this._jmuzup;
			}
			set
			{
				if ((this._jmuzup != value))
				{
					this.OnjmuzupChanging(value);
					this.SendPropertyChanging();
					this._jmuzup = value;
					this.SendPropertyChanged("jmuzup");
					this.OnjmuzupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fundusz", DbType="Int NOT NULL")]
		public int fundusz
		{
			get
			{
				return this._fundusz;
			}
			set
			{
				if ((this._fundusz != value))
				{
					this.OnfunduszChanging(value);
					this.SendPropertyChanging();
					this._fundusz = value;
					this.SendPropertyChanged("fundusz");
					this.OnfunduszChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odwrotneObc", DbType="SmallInt NOT NULL")]
		public short odwrotneObc
		{
			get
			{
				return this._odwrotneObc;
			}
			set
			{
				if ((this._odwrotneObc != value))
				{
					this.OnodwrotneObcChanging(value);
					this.SendPropertyChanging();
					this._odwrotneObc = value;
					this.SendPropertyChanged("odwrotneObc");
					this.OnodwrotneObcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vat50", DbType="SmallInt NOT NULL")]
		public short vat50
		{
			get
			{
				return this._vat50;
			}
			set
			{
				if ((this._vat50 != value))
				{
					this.Onvat50Changing(value);
					this.SendPropertyChanging();
					this._vat50 = value;
					this.SendPropertyChanged("vat50");
					this.Onvat50Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TW_TW", Storage="_TWs", ThisKey="id", OtherKey="rodzaj")]
		public EntitySet<TW> TWs
		{
			get
			{
				return this._TWs;
			}
			set
			{
				this._TWs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TW_TW", Storage="_TW1", ThisKey="rodzaj", OtherKey="id", IsForeignKey=true)]
		public TW TW1
		{
			get
			{
				return this._TW1.Entity;
			}
			set
			{
				TW previousValue = this._TW1.Entity;
				if (((previousValue != value) 
							|| (this._TW1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TW1.Entity = null;
						previousValue.TWs.Remove(this);
					}
					this._TW1.Entity = value;
					if ((value != null))
					{
						value.TWs.Add(this);
						this._rodzaj = value.id;
					}
					else
					{
						this._rodzaj = default(Nullable<int>);
					}
					this.SendPropertyChanged("TW1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TWs(TW entity)
		{
			this.SendPropertyChanging();
			entity.TW1 = this;
		}
		
		private void detach_TWs(TW entity)
		{
			this.SendPropertyChanging();
			entity.TW1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="HM.SF_PRICEBOOKS")]
	public partial class SF_PRICEBOOK
	{
		
		private int _Id;
		
		private double _UnitPrice;
		
		private string _CurrencyIsoCode;
		
		private System.Nullable<bool> _IsActive;
		
		private string _Lookup_Pricebook;
		
		private string _Lookup_ProductCode;
		
		public SF_PRICEBOOK()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitPrice", DbType="Float NOT NULL")]
		public double UnitPrice
		{
			get
			{
				return this._UnitPrice;
			}
			set
			{
				if ((this._UnitPrice != value))
				{
					this._UnitPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrencyIsoCode", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string CurrencyIsoCode
		{
			get
			{
				return this._CurrencyIsoCode;
			}
			set
			{
				if ((this._CurrencyIsoCode != value))
				{
					this._CurrencyIsoCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lookup_Pricebook", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Lookup_Pricebook
		{
			get
			{
				return this._Lookup_Pricebook;
			}
			set
			{
				if ((this._Lookup_Pricebook != value))
				{
					this._Lookup_Pricebook = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lookup_ProductCode", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Lookup_ProductCode
		{
			get
			{
				return this._Lookup_ProductCode;
			}
			set
			{
				if ((this._Lookup_ProductCode != value))
				{
					this._Lookup_ProductCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="HM.SF_ACCOUNTS")]
	public partial class SF_ACCOUNT
	{
		
		private int _Id;
		
		private string _SFDCRecordID;
		
		private string _EM_Account_Number__c;
		
		private string _Name;
		
		private string _BillingStreet;
		
		private string _BillingPostalCode;
		
		private string _BillingCity;
		
		private string _BillingStateCode;
		
		private string _BillingCountryCode;
		
		private string _Phone;
		
		private string _Fax;
		
		private string _Website;
		
		private string _EM_eMail_Address__c;
		
		private string _CurrencyIsoCode;
		
		private string _EM_Sort_Indicator__c;
		
		private string _EM_Customer_since__c;
		
		private System.Nullable<bool> _EM_Symphony_RMS__c;
		
		private System.Nullable<bool> _EM_Webshop_Customer__c;
		
		private System.Nullable<bool> _EM_Rental_Customer__c;
		
		private System.Nullable<bool> _EM_Delivery_Order_block__c;
		
		private System.Nullable<double> _EM_Credit_Limit__c;
		
		private string _EM_Payment_Terms__c;
		
		private bool _EM_Status__c;
		
		private string _EM_Language__c;
		
		private string _EM_Customer_Type__c;
		
		private string _EM_Subtype__c;
		
		private string _EM_Former_Account_Number__c;
		
		private string _Lookup_Buying_Group_Account_Number;
		
		private string _Lookup_Pricebook;
		
		private string _Lookup_RecordType;
		
		private string _Lookup_Parent_Account_Number;
		
		private string _EM_TAX_ID_Number__c;
		
		private string _EM_Local_Currency__c;
		
		private string _EM_Sales_Rep__c;
		
		public SF_ACCOUNT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SFDCRecordID", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string SFDCRecordID
		{
			get
			{
				return this._SFDCRecordID;
			}
			set
			{
				if ((this._SFDCRecordID != value))
				{
					this._SFDCRecordID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EM_Account_Number__c", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EM_Account_Number__c
		{
			get
			{
				return this._EM_Account_Number__c;
			}
			set
			{
				if ((this._EM_Account_Number__c != value))
				{
					this._EM_Account_Number__c = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingStreet", DbType="NVarChar(82)")]
		public string BillingStreet
		{
			get
			{
				return this._BillingStreet;
			}
			set
			{
				if ((this._BillingStreet != value))
				{
					this._BillingStreet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingPostalCode", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string BillingPostalCode
		{
			get
			{
				return this._BillingPostalCode;
			}
			set
			{
				if ((this._BillingPostalCode != value))
				{
					this._BillingPostalCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingCity", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BillingCity
		{
			get
			{
				return this._BillingCity;
			}
			set
			{
				if ((this._BillingCity != value))
				{
					this._BillingCity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingStateCode", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string BillingStateCode
		{
			get
			{
				return this._BillingStateCode;
			}
			set
			{
				if ((this._BillingStateCode != value))
				{
					this._BillingStateCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingCountryCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BillingCountryCode
		{
			get
			{
				return this._BillingCountryCode;
			}
			set
			{
				if ((this._BillingCountryCode != value))
				{
					this._BillingCountryCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Website
		{
			get
			{
				return this._Website;
			}
			set
			{
				if ((this._Website != value))
				{
					this._Website = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EM_eMail_Address__c", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string EM_eMail_Address__c
		{
			get
			{
				return this._EM_eMail_Address__c;
			}
			set
			{
				if ((this._EM_eMail_Address__c != value))
				{
					this._EM_eMail_Address__c = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrencyIsoCode", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string CurrencyIsoCode
		{
			get
			{
				return this._CurrencyIsoCode;
			}
			set
			{
				if ((this._CurrencyIsoCode != value))
				{
					this._CurrencyIsoCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EM_Sort_Indicator__c", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string EM_Sort_Indicator__c
		{
			get
			{
				return this._EM_Sort_Indicator__c;
			}
			set
			{
				if ((this._EM_Sort_Indicator__c != value))
				{
					this._EM_Sort_Indicator__c = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EM_Customer_since__c", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string EM_Customer_since__c
		{
			get
			{
				return this._EM_Customer_since__c;
			}
			set
			{
				if ((this._EM_Customer_since__c != value))
				{
					this._EM_Customer_since__c = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EM_Symphony_RMS__c", DbType="Bit")]
		public System.Nullable<bool> EM_Symphony_RMS__c
		{
			get
			{
				return this._EM_Symphony_RMS__c;
			}
			set
			{
				if ((this._EM_Symphony_RMS__c != value))
				{
					this._EM_Symphony_RMS__c = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EM_Webshop_Customer__c", DbType="Bit")]
		public System.Nullable<bool> EM_Webshop_Customer__c
		{
			get
			{
				return this._EM_Webshop_Customer__c;
			}
			set
			{
				if ((this._EM_Webshop_Customer__c != value))
				{
					this._EM_Webshop_Customer__c = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EM_Rental_Customer__c", DbType="Bit")]
		public System.Nullable<bool> EM_Rental_Customer__c
		{
			get
			{
				return this._EM_Rental_Customer__c;
			}
			set
			{
				if ((this._EM_Rental_Customer__c != value))
				{
					this._EM_Rental_Customer__c = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EM_Delivery_Order_block__c", DbType="Bit")]
		public System.Nullable<bool> EM_Delivery_Order_block__c
		{
			get
			{
				return this._EM_Delivery_Order_block__c;
			}
			set
			{
				if ((this._EM_Delivery_Order_block__c != value))
				{
					this._EM_Delivery_Order_block__c = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EM_Credit_Limit__c", DbType="Float")]
		public System.Nullable<double> EM_Credit_Limit__c
		{
			get
			{
				return this._EM_Credit_Limit__c;
			}
			set
			{
				if ((this._EM_Credit_Limit__c != value))
				{
					this._EM_Credit_Limit__c = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EM_Payment_Terms__c", DbType="VarChar(111) NOT NULL", CanBeNull=false)]
		public string EM_Payment_Terms__c
		{
			get
			{
				return this._EM_Payment_Terms__c;
			}
			set
			{
				if ((this._EM_Payment_Terms__c != value))
				{
					this._EM_Payment_Terms__c = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EM_Status__c", DbType="Bit NOT NULL")]
		public bool EM_Status__c
		{
			get
			{
				return this._EM_Status__c;
			}
			set
			{
				if ((this._EM_Status__c != value))
				{
					this._EM_Status__c = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EM_Language__c", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string EM_Language__c
		{
			get
			{
				return this._EM_Language__c;
			}
			set
			{
				if ((this._EM_Language__c != value))
				{
					this._EM_Language__c = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EM_Customer_Type__c", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string EM_Customer_Type__c
		{
			get
			{
				return this._EM_Customer_Type__c;
			}
			set
			{
				if ((this._EM_Customer_Type__c != value))
				{
					this._EM_Customer_Type__c = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EM_Subtype__c", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string EM_Subtype__c
		{
			get
			{
				return this._EM_Subtype__c;
			}
			set
			{
				if ((this._EM_Subtype__c != value))
				{
					this._EM_Subtype__c = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EM_Former_Account_Number__c", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string EM_Former_Account_Number__c
		{
			get
			{
				return this._EM_Former_Account_Number__c;
			}
			set
			{
				if ((this._EM_Former_Account_Number__c != value))
				{
					this._EM_Former_Account_Number__c = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lookup_Buying_Group_Account_Number", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Lookup_Buying_Group_Account_Number
		{
			get
			{
				return this._Lookup_Buying_Group_Account_Number;
			}
			set
			{
				if ((this._Lookup_Buying_Group_Account_Number != value))
				{
					this._Lookup_Buying_Group_Account_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lookup_Pricebook", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string Lookup_Pricebook
		{
			get
			{
				return this._Lookup_Pricebook;
			}
			set
			{
				if ((this._Lookup_Pricebook != value))
				{
					this._Lookup_Pricebook = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lookup_RecordType", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string Lookup_RecordType
		{
			get
			{
				return this._Lookup_RecordType;
			}
			set
			{
				if ((this._Lookup_RecordType != value))
				{
					this._Lookup_RecordType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lookup_Parent_Account_Number", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Lookup_Parent_Account_Number
		{
			get
			{
				return this._Lookup_Parent_Account_Number;
			}
			set
			{
				if ((this._Lookup_Parent_Account_Number != value))
				{
					this._Lookup_Parent_Account_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EM_TAX_ID_Number__c", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string EM_TAX_ID_Number__c
		{
			get
			{
				return this._EM_TAX_ID_Number__c;
			}
			set
			{
				if ((this._EM_TAX_ID_Number__c != value))
				{
					this._EM_TAX_ID_Number__c = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EM_Local_Currency__c", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string EM_Local_Currency__c
		{
			get
			{
				return this._EM_Local_Currency__c;
			}
			set
			{
				if ((this._EM_Local_Currency__c != value))
				{
					this._EM_Local_Currency__c = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EM_Sales_Rep__c", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string EM_Sales_Rep__c
		{
			get
			{
				return this._EM_Sales_Rep__c;
			}
			set
			{
				if ((this._EM_Sales_Rep__c != value))
				{
					this._EM_Sales_Rep__c = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mplerpsw_configuration")]
	public partial class mplerpsw_configuration : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _FKey;
		
		private string _Value;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFKeyChanging(string value);
    partial void OnFKeyChanged();
    partial void OnValueChanging(string value);
    partial void OnValueChanged();
    #endregion
		
		public mplerpsw_configuration()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKey", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string FKey
		{
			get
			{
				return this._FKey;
			}
			set
			{
				if ((this._FKey != value))
				{
					this.OnFKeyChanging(value);
					this.SendPropertyChanging();
					this._FKey = value;
					this.SendPropertyChanged("FKey");
					this.OnFKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="NVarChar(200)")]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnValueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("Value");
					this.OnValueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mplerpsw_rights")]
	public partial class mplerpsw_right : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _UserName;
		
		private string _UserPassword;
		
		private bool _CheckOrder;
		
		private bool _CreateSalesOrder;
		
		private bool _GetPricingForQuote;
		
		private bool _GetPricingForOrder;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnUserPasswordChanging(string value);
    partial void OnUserPasswordChanged();
    partial void OnCheckOrderChanging(bool value);
    partial void OnCheckOrderChanged();
    partial void OnCreateSalesOrderChanging(bool value);
    partial void OnCreateSalesOrderChanged();
    partial void OnGetPricingForQuoteChanging(bool value);
    partial void OnGetPricingForQuoteChanged();
    partial void OnGetPricingForOrderChanging(bool value);
    partial void OnGetPricingForOrderChanged();
    #endregion
		
		public mplerpsw_right()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserPassword", DbType="NVarChar(200)")]
		public string UserPassword
		{
			get
			{
				return this._UserPassword;
			}
			set
			{
				if ((this._UserPassword != value))
				{
					this.OnUserPasswordChanging(value);
					this.SendPropertyChanging();
					this._UserPassword = value;
					this.SendPropertyChanged("UserPassword");
					this.OnUserPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckOrder", DbType="Bit NOT NULL")]
		public bool CheckOrder
		{
			get
			{
				return this._CheckOrder;
			}
			set
			{
				if ((this._CheckOrder != value))
				{
					this.OnCheckOrderChanging(value);
					this.SendPropertyChanging();
					this._CheckOrder = value;
					this.SendPropertyChanged("CheckOrder");
					this.OnCheckOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateSalesOrder", DbType="Bit NOT NULL")]
		public bool CreateSalesOrder
		{
			get
			{
				return this._CreateSalesOrder;
			}
			set
			{
				if ((this._CreateSalesOrder != value))
				{
					this.OnCreateSalesOrderChanging(value);
					this.SendPropertyChanging();
					this._CreateSalesOrder = value;
					this.SendPropertyChanged("CreateSalesOrder");
					this.OnCreateSalesOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GetPricingForQuote", DbType="Bit NOT NULL")]
		public bool GetPricingForQuote
		{
			get
			{
				return this._GetPricingForQuote;
			}
			set
			{
				if ((this._GetPricingForQuote != value))
				{
					this.OnGetPricingForQuoteChanging(value);
					this.SendPropertyChanging();
					this._GetPricingForQuote = value;
					this.SendPropertyChanged("GetPricingForQuote");
					this.OnGetPricingForQuoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GetPricingForOrder", DbType="Bit NOT NULL")]
		public bool GetPricingForOrder
		{
			get
			{
				return this._GetPricingForOrder;
			}
			set
			{
				if ((this._GetPricingForOrder != value))
				{
					this.OnGetPricingForOrderChanging(value);
					this.SendPropertyChanging();
					this._GetPricingForOrder = value;
					this.SendPropertyChanged("GetPricingForOrder");
					this.OnGetPricingForOrderChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SF_PRICEBOOKS_GROSS")]
	public partial class SF_PRICEBOOKS_GROSS
	{
		
		private int _id;
		
		private double _NettUnitPrice;
		
		private double _GrossUnitPrice;
		
		private double _vat;
		
		private short _typ;
		
		private string _CurrencyIsoCode;
		
		private System.Nullable<bool> _IsActive;
		
		private string _Lookup_Pricebook;
		
		private string _Lookup_ProductCode;
		
		private string _nazwa;
		
		private System.Nullable<double> _stan;
		
		private int _TwId;
		
		public SF_PRICEBOOKS_GROSS()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NettUnitPrice", DbType="Float NOT NULL")]
		public double NettUnitPrice
		{
			get
			{
				return this._NettUnitPrice;
			}
			set
			{
				if ((this._NettUnitPrice != value))
				{
					this._NettUnitPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrossUnitPrice", DbType="Float NOT NULL")]
		public double GrossUnitPrice
		{
			get
			{
				return this._GrossUnitPrice;
			}
			set
			{
				if ((this._GrossUnitPrice != value))
				{
					this._GrossUnitPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vat", DbType="Float NOT NULL")]
		public double vat
		{
			get
			{
				return this._vat;
			}
			set
			{
				if ((this._vat != value))
				{
					this._vat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typ", DbType="SmallInt NOT NULL")]
		public short typ
		{
			get
			{
				return this._typ;
			}
			set
			{
				if ((this._typ != value))
				{
					this._typ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrencyIsoCode", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string CurrencyIsoCode
		{
			get
			{
				return this._CurrencyIsoCode;
			}
			set
			{
				if ((this._CurrencyIsoCode != value))
				{
					this._CurrencyIsoCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lookup_Pricebook", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Lookup_Pricebook
		{
			get
			{
				return this._Lookup_Pricebook;
			}
			set
			{
				if ((this._Lookup_Pricebook != value))
				{
					this._Lookup_Pricebook = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lookup_ProductCode", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Lookup_ProductCode
		{
			get
			{
				return this._Lookup_ProductCode;
			}
			set
			{
				if ((this._Lookup_ProductCode != value))
				{
					this._Lookup_ProductCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nazwa
		{
			get
			{
				return this._nazwa;
			}
			set
			{
				if ((this._nazwa != value))
				{
					this._nazwa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stan", DbType="Float")]
		public System.Nullable<double> stan
		{
			get
			{
				return this._stan;
			}
			set
			{
				if ((this._stan != value))
				{
					this._stan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TwId", DbType="Int NOT NULL")]
		public int TwId
		{
			get
			{
				return this._TwId;
			}
			set
			{
				if ((this._TwId != value))
				{
					this._TwId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SF_ACTIVITIES_LOG")]
	public partial class SF_ACTIVITIES_LOG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private short _typOperacji;
		
		private string _operacja;
		
		private System.DateTime _dataOperacji;
		
		private string _user;
		
		private System.Xml.Linq.XElement _PlikXML;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntypOperacjiChanging(short value);
    partial void OntypOperacjiChanged();
    partial void OnoperacjaChanging(string value);
    partial void OnoperacjaChanged();
    partial void OndataOperacjiChanging(System.DateTime value);
    partial void OndataOperacjiChanged();
    partial void OnuserChanging(string value);
    partial void OnuserChanged();
    partial void OnPlikXMLChanging(System.Xml.Linq.XElement value);
    partial void OnPlikXMLChanged();
    #endregion
		
		public SF_ACTIVITIES_LOG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typOperacji", DbType="SmallInt NOT NULL")]
		public short typOperacji
		{
			get
			{
				return this._typOperacji;
			}
			set
			{
				if ((this._typOperacji != value))
				{
					this.OntypOperacjiChanging(value);
					this.SendPropertyChanging();
					this._typOperacji = value;
					this.SendPropertyChanged("typOperacji");
					this.OntypOperacjiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operacja", DbType="NVarChar(130) NOT NULL", CanBeNull=false)]
		public string operacja
		{
			get
			{
				return this._operacja;
			}
			set
			{
				if ((this._operacja != value))
				{
					this.OnoperacjaChanging(value);
					this.SendPropertyChanging();
					this._operacja = value;
					this.SendPropertyChanged("operacja");
					this.OnoperacjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataOperacji", DbType="DateTime NOT NULL")]
		public System.DateTime dataOperacji
		{
			get
			{
				return this._dataOperacji;
			}
			set
			{
				if ((this._dataOperacji != value))
				{
					this.OndataOperacjiChanging(value);
					this.SendPropertyChanging();
					this._dataOperacji = value;
					this.SendPropertyChanged("dataOperacji");
					this.OndataOperacjiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[user]", Storage="_user", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string user
		{
			get
			{
				return this._user;
			}
			set
			{
				if ((this._user != value))
				{
					this.OnuserChanging(value);
					this.SendPropertyChanging();
					this._user = value;
					this.SendPropertyChanged("user");
					this.OnuserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlikXML", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement PlikXML
		{
			get
			{
				return this._PlikXML;
			}
			set
			{
				if ((this._PlikXML != value))
				{
					this.OnPlikXMLChanging(value);
					this.SendPropertyChanging();
					this._PlikXML = value;
					this.SendPropertyChanged("PlikXML");
					this.OnPlikXMLChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class hm_GetUpustIndywResult
	{
		
		private int _id;
		
		private System.Nullable<int> _idPm;
		
		private System.Nullable<int> _idPd;
		
		private short _aktywna;
		
		private short _typ;
		
		private short _subtyp;
		
		private double _cena;
		
		private string _waluta;
		
		private System.Nullable<System.DateTime> _datastart;
		
		public hm_GetUpustIndywResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPm", DbType="Int")]
		public System.Nullable<int> idPm
		{
			get
			{
				return this._idPm;
			}
			set
			{
				if ((this._idPm != value))
				{
					this._idPm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPd", DbType="Int")]
		public System.Nullable<int> idPd
		{
			get
			{
				return this._idPd;
			}
			set
			{
				if ((this._idPd != value))
				{
					this._idPd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aktywna", DbType="SmallInt NOT NULL")]
		public short aktywna
		{
			get
			{
				return this._aktywna;
			}
			set
			{
				if ((this._aktywna != value))
				{
					this._aktywna = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typ", DbType="SmallInt NOT NULL")]
		public short typ
		{
			get
			{
				return this._typ;
			}
			set
			{
				if ((this._typ != value))
				{
					this._typ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subtyp", DbType="SmallInt NOT NULL")]
		public short subtyp
		{
			get
			{
				return this._subtyp;
			}
			set
			{
				if ((this._subtyp != value))
				{
					this._subtyp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cena", DbType="Float NOT NULL")]
		public double cena
		{
			get
			{
				return this._cena;
			}
			set
			{
				if ((this._cena != value))
				{
					this._cena = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_waluta", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string waluta
		{
			get
			{
				return this._waluta;
			}
			set
			{
				if ((this._waluta != value))
				{
					this._waluta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datastart", DbType="DateTime")]
		public System.Nullable<System.DateTime> datastart
		{
			get
			{
				return this._datastart;
			}
			set
			{
				if ((this._datastart != value))
				{
					this._datastart = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
