//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_kandydata.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Test_kandydata.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Code: MEDESF99] Error connection with ERP database occured..
        /// </summary>
        internal static string ConnectionErrorDAL {
            get {
                return ResourceManager.GetString("ConnectionErrorDAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Code: 500] Net price value goe below zero after discount.
        /// </summary>
        internal static string NetPriceIsBelowZeroAfterDiscount {
            get {
                return ResourceManager.GetString("NetPriceIsBelowZeroAfterDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Code: 203] Product can not be found in  contractor pricebook.
        /// </summary>
        internal static string ProductCantBeFoundInPricebook {
            get {
                return ResourceManager.GetString("ProductCantBeFoundInPricebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Code: MEDESF06] Product can not be found in ERP database..
        /// </summary>
        internal static string ProductIsNotInTheDatabase {
            get {
                return ResourceManager.GetString("ProductIsNotInTheDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Code: 204] Product is out of stock.
        /// </summary>
        internal static string ProductIsOutOfStock {
            get {
                return ResourceManager.GetString("ProductIsOutOfStock", resourceCulture);
            }
        }
    }
}
